## Solving XOR problem using deep learning neural network

In [ ]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense

In [ ]:
model = Sequential()                                 #to make supervised learning model
model.add(Dense(units=2, activation='relu', input_dim=2))
model.add(Dense(units=2, activation='relu'))
model.add(Dense(units=1, activation='sigmoid'))      #binary Output therefore loss function used is sigmoid

In [ ]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics='accuracy')
print(model.summary())                               #(4 weights , 1 bias)
print(model.get_weights())                           #initial weights

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 2)                 6         
                                                                 
 dense_4 (Dense)             (None, 2)                 6         
                                                                 
 dense_5 (Dense)             (None, 1)                 3         
                                                                 
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________
None
[array([[-0.01816452, -1.2223636 ],
       [ 0.6161238 ,  0.31936574]], dtype=float32), array([0., 0.], dtype=float32), array([[ 0.7532003 ,  0.37858105],
       [ 0.89843714, -0.462673  ]], dtype=float32), array([0., 0.], dtype=float32), array([[ 1.1688038 ],
       [-0.90824974]], dtype=float32), array([0.], dtype

In [ ]:
X = np.array([[0.,0.],[0.,1.],[1.,0.],[1.,1.]])
print(X)

[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]


In [ ]:
y = np.array([0.,1.,1.,0.])
print(y)

[0. 1. 1. 0.]


In [ ]:
model.fit(X, y, epochs=100, batch_size=4)

Epoch 1/100
1/1 [==============================] - 0s 322ms/step - loss: 0.6559 - accuracy: 0.5000
Epoch 2/100
1/1 [==============================] - 0s 2ms/step - loss: 0.6552 - accuracy: 0.5000
Epoch 3/100
1/1 [==============================] - 0s 3ms/step - loss: 0.6545 - accuracy: 0.5000
Epoch 4/100
1/1 [==============================] - 0s 3ms/step - loss: 0.6539 - accuracy: 0.5000
Epoch 5/100
1/1 [==============================] - 0s 3ms/step - loss: 0.6532 - accuracy: 0.5000
Epoch 6/100
1/1 [==============================] - 0s 2ms/step - loss: 0.6525 - accuracy: 0.5000
Epoch 7/100
1/1 [==============================] - 0s 3ms/step - loss: 0.6519 - accuracy: 0.5000
Epoch 8/100
1/1 [==============================] - 0s 3ms/step - loss: 0.6512 - accuracy: 0.5000
Epoch 9/100
1/1 [==============================] - 0s 2ms/step - loss: 0.6505 - accuracy: 0.5000
Epoch 10/100
1/1 [==============================] - 0s 2ms/step - loss: 0.6499 - accuracy: 0.5000
Epoch 11/100
1/1 [=========

In [ ]:
predictions = model.predict(X)
predictions

1/1 [==============================] - 0s 56ms/step


array([[0.47117737],
       [0.69934   ],
       [0.45802256],
       [0.46239433]], dtype=float32)

In [ ]:
def prob_Bin(_list):
    pred = []
    for i in _list:
        if i>=0.5:
            pred.append(1)
        else:
            pred.append(0)
    return pred

In [ ]:
prob_Bin(predictions)

[0, 1, 0, 0]

In [ ]:
y

array([0., 1., 1., 0.])

Gave 75% accuracy